#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

DRRT_ROOT="${SCRIPT_DIR}/../.."

. "$SCRIPT_DIR/shipIndex.conf"

REGEX='({854,|{863,|{838,|{833,|{273,|{927,|{928,|{929,|{930,|{931,|{932,|{933,|{934,|{935,|{936,|{937,|{938,|{939,|{940,|{941,|{942,|{943,|{953,|{954,|{955,|{956,|{320,|{11104,|{12130,|{15010,|{15142,|{15144,|{15146,)'

if [[ -f "$SCRIPT_DIR/.checking.lua.gz" ]]; then
    rm "$SCRIPT_DIR/.checking.lua.gz"
fi

if [[ -f "$SCRIPT_DIR/.checking.lua" ]]; then
    rm "$SCRIPT_DIR/.checking.lua"
fi

for i in ${participants[@]}; do
    cp "$i" "$SCRIPT_DIR/.checking.lua.gz"

    gunzip "$SCRIPT_DIR/.checking.lua.gz" 

    grep "$REGEX" "$SCRIPT_DIR/.checking.lua"

    rm "$SCRIPT_DIR/.checking.lua"
done
