#!/bin/bash

set -e

jobs=0

AWK_STRIPPER="$(readlink -e stripper.awk)"

if [ ! -n "$AWK" ]; then
    AWK=awk
fi

function schedule_it {
    # $1 = rounds
    # $2 = alliance size
    # $3 = team count
    echo "making schedule '${3}_${2}v${2}.txt'..."

    MatchMaker -a "$2" -r "$1" -t "$3" -b > "${3}_${2}v${2}.txt"

    $AWK -f "$AWK_STRIPPER" "${3}_${2}v${2}.txt"

    mv "${3}_${2}v${2}.csv" ../out
}


if [ ! -d schedules ]; then
    echo "creating 'schedules' directory"
    mkdir schedules
fi

cd schedules

if [ ! -d out ]; then
    echo "creating 'schedules/out' directory"
    mkdir out
fi

if [ "$(ls -A out/)" ]; then
    rm out/*
fi

for i in 2 3 4; do
    DIRNAME="${i}v${i}"
    
    if [ ! -d "${DIRNAME}" ]; then
        mkdir "${DIRNAME}"
    else
        if [ "$(ls -A out/)" ]; then
            rm "${DIRNAME}"/*
        fi
    fi

    cd "./${DIRNAME}"
    
    parallel schedule_it {1} {2} {3} ::: $1 ::: $(seq 1 100) ::: $(seq 2 4)

    # for j in $(seq $(expr "$i" '*' '2') $2); do

    #     if [ $jobs -ge 14 ]; then
    #         wait -n
    #         let 'jobs -= 1'
    #     fi

    #     schedule_it "$1" "$i" "$j" &
    #     let 'jobs += 1'
    # done
    
    cd ..
done

wait
