#!/bin/bash

set -e

jobs=0

function awk_it {
    cd "$1"

    echo "converting ${1} schedules from raw format to csv..."

    if [ "$( grep -Ri '^ERROR:.*silly' | awk -F: '{ print $1 }' )" ]; then
        rm $( grep -Ri '^ERROR:.*silly' | awk -F: '{ print $1 }' )
    fi

    awk -f ../../stripper.awk *.txt

    mv *.csv "../out/"
}

if [ ! -d schedules ]; then
    echo "creating 'schedules' directory"

    mkdir schedules
fi

cd schedules

if [ ! -d out ]; then
    echo "creating 'schedules/out' directory"

    mkdir out
fi

if [ "$(ls -A out/)" ]; then
    rm out/*
fi

for i in 2 3 4; do

    DIRNAME="${i}v${i}"
    
    if [ ! -d "${DIRNAME}" ]; then
        mkdir "${DIRNAME}"
    else
        if [ "$(ls -A out/)" ]; then
            rm "${DIRNAME}"/*
        fi
    fi

    cd "./${DIRNAME}"

    for j in $(seq 4 $2); do

        if [ $jobs -ge 14 ]; then
            wait -n

            let 'jobs -= 1'
        fi

        echo "making schedule '${j}_${DIRNAME}.txt'..."

        MatchMaker -a "$i" -r "$1" -t "$j" -f > "${j}_${DIRNAME}.txt" 2> /dev/null &
        let 'jobs += 1'
    done
    
    cd ..

    wait
    jobs=0

    echo preawk

    awk_it "${DIRNAME}" &
    let 'jobs += 1'
done

wait
